### TEST BEZ KLUCZA API (Powinien zwrócić błąd 401)
POST https://localhost:7072/api/machine/1/heartbeat
Content-Type: application/json

### TEST "HEARTBEAT" Z KLUCZEM (Powinien zwrócić 200 OK)
POST https://localhost:7072/api/machine/1/heartbeat
Content-Type: application/json
X-API-KEY: Zmp5pH2Na2h7RqgRRZWf7GcMGnz6TDxR

### TEST SPRZEDAŻY Z KLUCZEM (Powinien zwrócić 201 Created)
POST https://localhost:7072/api/machine/1/sale
Content-Type: application/json
X-API-KEY: Zmp5pH2Na2h7RqgRRZWf7GcMGnz6TDxR

{
  "productId": 2
}