// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VendingManager.Data;

#nullable disable

namespace VendingManager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251020210512_AddSeedData")]
    partial class AddSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("VendingManager.Models.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastContact")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Machines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastContact = new DateTime(2025, 10, 20, 11, 55, 0, 0, DateTimeKind.Unspecified),
                            Location = "Hol wejściowy, Budynek A",
                            Name = "Automat GŁÓWNY",
                            Status = "Online"
                        },
                        new
                        {
                            Id = 2,
                            LastContact = new DateTime(2025, 10, 20, 4, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Korytarz przy windach",
                            Name = "Automat PIĘTRO 2",
                            Status = "Offline"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
